# Generated by Django 5.2.6 on 2025-09-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiimagesolution',
            name='solution_type',
            field=models.CharField(choices=[('image', 'Image Analysis'), ('document', 'Document Analysis'), ('text_chat', 'Text Chat')], default='image', max_length=20),
        ),
    ]
