# Generated by Django 5.2.6 on 2025-09-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
