# Generated by Django 5.2.6 on 2025-09-20 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiconversation',
            options={},
        ),
        migrations.RemoveField(
            model_name='aiconversation',
            name='session_id',
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='image_solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.aiimagesolution'),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='aiconversation',
            table=None,
        ),
    ]
